############################################
###       APPLICATION PARAMETERS         ###
############################################

Datasource_address="127.0.0.1"
Datasource_port=3303
Datasource_username="orchestrator"
Datasource_password="KbgD2mTr8DQ4vtc"
Datasource_database="arrowhead"


# Orchestrator web-server parameters
Server_address="192.168.11.19"
Server_port=8441

############################################
###       CUSTOM PARAMETERS              ###
############################################

# Name of the core system
Core_system_name="orchestrator"

# Show all request/response in debug log
Log_all_request_and_response=false

# Service Registry web-server parameters (to register the Orchestrator's services)
Sr_address="127.0.0.1"
Sr_port=8443

############################################
###           SECURE MODE                ###
############################################

# configure secure mode

# Set this to false to disable https mode
Server_ssl_enabled=true


Server_ssl_key_store="certificates/orchestrator.pem"
Server_ssl_key_store_file="certificates/orchestrator.key"
Server_ssl_client_auth="none" #"need"
Server_ssl_trust_store="../certificates/testcloud2/testcloud2.pem"
#Server_ssl_trust_store_password="123456"

#Disable_hostname_verifier=false
