############################################
###       APPLICATION PARAMETERS         ###
############################################

Datasource_address="127.0.0.1"
Datasource_port=3303
Datasource_username="authorization"
Datasource_password="hqZFUkuHxhekio3"
Datasource_database="arrowhead"


# Authorization web-server parameters
Server_address="192.168.11.22"
Server_port=8445

############################################
###       CUSTOM PARAMETERS              ###
############################################

# Name of the core system
Core_system_name="authorization"

# Service Registry web-server parameters (to register the Authorizarion's services)
sr_address="192.168.11.22"
sr_port=8443

############################################
###           SECURE MODE                ###
############################################

# configure secure mode

# Set this to false to disable https mode
Server_ssl_enabled=false

Server_ssl_key_store="certificates/authorization.pem"
Server_ssl_key_store_file="certificates/authorization.key"
Server_ssl_client_auth="need" #"none" #"need"
Server_ssl_trust_store="certificates/ca.pem"
#Server_ssl_trust_store_password="123456"

#Disable_hostname_verifier=false
