############################################
###       APPLICATION PARAMETERS         ###
############################################

Datasource_address="127.0.0.1"
Datasource_port=3303
Datasource_username="certificate_authority"
Datasource_password="FsdG6Kgf9QpPfv2"
Datasource_database="arrowhead"


# Certificate Authority web-server parameters
Server_address="127.0.0.1"
Server_port=8448

############################################
###       CUSTOM PARAMETERS              ###
############################################

# Name of the core system
Core_system_name="certificateauthority"

# Show all request/response in debug log
Log_all_request_and_response=false

# Service Registry web-server parameters (to register the Orchestrator's services)
Sr_address="127.0.0.1"
Sr_port=8443

############################################
###           SECURE MODE                ###
############################################

# configure secure mode

# Set this to false to disable https mode
Server_ssl_enabled=true

Server_ssl_key_store="certificates/certificateauthority.pem"
Server_ssl_key_store_file="certificates/certificateauthority.key"
Server_ssl_client_auth="need" #"none" #"need"
Server_ssl_trust_store="../certificates/testcloud2/testcloud2.pem"
#Server_ssl_trust_store_password="123456"
